#lang eopl
(require rackunit)
(require "base.rkt")

(define-datatype expval expval?
  (num-val (num number?))
  (bool-val (bool boolean?))
  )

(define (expval->num val)
  (cases expval val
         (num-val (num) num)
         (else (report-expval-extractor-error 'num val))))

(define (expval->bool val)
  (cases expval val
         (bool-val (bool) bool)
         (else (report-expval-extractor-error 'bool val))))

(define (run s)
  (value-of-program (scan&parse s)))

(define init-env
  empty-env)

(define-datatype program program?
  (a-program (exp expression?)))

(define grammar-let
  '(;; (program (expression) a-progam)
    (expression (number) const-exp)
    (expression (identifier) var-exp)
    (expression ("zero?" expression) zero?-exp)
    (expression ("equal?" expression "," expression) eq?-exp)
    (expression ("greater?" expression "," expression) gt?-exp)
    (expression ("less?" expression "," expression) ls?-exp)
    (expression ("if" expression "then" expression "else" expression) if-exp)
    (expression ("let" identifier "=" expression "in" expression) let-exp)
    (expression ("minus" "(" expression ")") minus-exp)
    (expression ("-" expression "," expression) diff-exp)
    (expression ("+" expression "," expression) add-exp)
    (expression ("*" expression "," expression) mul-exp)
    (expression ("/" expression "," expression) div-exp)
    (expression ("emptylist") emptylist-exp)
    (expression ("cons" expression "," expression) cons-exp)
    (expression ("car" expression) car-exp)
    (expression ("cdr" expression) cdr-exp)
    (expression ("null?" expression) null?-exp)
    (expression ("list" "(" (separated-list expression ",") ")") list-exp)
    ))

(sllgen:make-define-datatypes scanner-spec-a grammar-let)

(define scan&parse
  (sllgen:make-string-parser scanner-spec-a grammar-let))


(define (value-of-program pgm)
  (cases program pgm
         (a-program (exp1)
                    (value-of exp1 (init-env)))))

(define (value-of-exp e)
  (value-of (scan&parse e)
            (init-env)))

(define (value-of exp env)
  (cases expression exp
         (const-exp (num) (num-val num))
         (var-exp (var) (apply-env env var))
         (diff-exp (exp1 exp2)
                   (let ((val1 (value-of exp1 env))
                         (val2 (value-of exp2 env)))
                     (let ((num1 (expval->num val1))
                           (num2 (expval->num val2)))
                       (num-val (- num1 num2)))))
         (zero?-exp (exp1)
                    (let ((val1 (value-of exp1 env)))
                      (let ((num1 (expval->num val1)))
                        (if (zero? num1)
                            (bool-val #t)
                            (bool-val #f)))))
         (eq?-exp (exp0 exp1)
                  (let ((val0 (value-of exp0 env))
                        (val1 (value-of exp1 env)))
                    (let ((num0 (expval->num val0))
                          (num1 (expval->num val1)))
                      (if (= num0 num1)
                          (bool-val #t)
                          (bool-val #f)))))
         (gt?-exp (exp0 exp1)
                  (let ((val0 (value-of exp0 env))
                        (val1 (value-of exp1 env)))
                    (let ((num0 (expval->num val0))
                          (num1 (expval->num val1)))
                      (if (> num0 num1)
                          (bool-val #t)
                          (bool-val #f)))))
         (ls?-exp (exp0 exp1)
                  (let ((val0 (value-of exp0 env))
                        (val1 (value-of exp1 env)))
                    (let ((num0 (expval->num val0))
                          (num1 (expval->num val1)))
                      (if (< num0 num1)
                          (bool-val #t)
                          (bool-val #f)))))
         (if-exp (exp1 exp2 exp3)
                 (let ((val1 (value-of exp1 env)))
                   (if (expval->bool val1)
                       (value-of exp2 env)
                       (value-of exp3 env))))
         (let-exp (var exp1 body)
                  (let ((val1 (value-of exp1 env)))
                    (value-of body
                              (extend-env var val1 env))))
         (minus-exp (exp0)
                    (let ((val0 (value-of exp0 env)))
                      (num-val (- (expval->num val0)))))
         (add-exp (exp0 exp1)
                  (let ((val0 (value-of exp0 env))
                        (val1 (value-of exp1 env)))
                    (let ((num0 (expval->num val0))
                          (num1 (expval->num val1)))
                      (num-val (+ num0 num1)))))
         (mul-exp (exp0 exp1)
                  (let ((val0 (value-of exp0 env))
                        (val1 (value-of exp1 env)))
                    (let ((num0 (expval->num val0))
                          (num1 (expval->num val1)))
                      (num-val (* num0 num1)))))
         (div-exp (exp0 exp1)
                  (let ((val0 (value-of exp0 env))
                        (val1 (value-of exp1 env)))
                    (let ((num0 (expval->num val0))
                          (num1 (expval->num val1)))
                      (num-val (quotient num0 num1)))))
         (emptylist-exp ()
                        '())
         (cons-exp (exp0 exp1)
                   (let ((val0 (value-of exp0 env))
                         (val1 (value-of exp1 env)))
                     (cons val0 val1)))
         (car-exp (exp0)
                   (let ((val0 (value-of exp0 env)))
                     (car val0)))
         (cdr-exp (exp0)
                  (let ((val0 (value-of exp0 env)))
                    (cdr val0)))
         (null?-exp (exp0)
                  (let ((val0 (value-of exp0 env)))
                    (if (null? val0)
                        (bool-val #t)
                        (bool-val #f))))
         (list-exp (exps)
                   (let ((vals (map (lambda (e)
                                      (value-of e env))
                                    exps)))
                     vals))
         ))

(check-equal? (value-of-exp "+ 1, 3")
              (num-val 4))